[package]
name = "member-a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustversion = { git = "https://github.com/dtolnay/rustversion" }
